name: 701-proj
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipython
  - ipykernel
  - scikit-learn
  - pip
  - pip:
      - torch
      - torchvision
      - unbabel-comet
      - d2l
      - huggingface_hub